[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.1"
num-complex = "0.4.6"
rustc-hash = "2.1.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "all_days"
harness = false

[profile.profiling]
debug = true
inherits = "release"